
export const ADD_CART_ITEM = 'ADD_CART_ITEM'; 
export const REOMVE_CART_ITEM = 'REOMVE_CART_ITEM';
export const CART_ITEM_RESET = 'CART_ITEM_RESET'


// export const CART_SAVE_SHIPPING_ADDRESS = 'CART_SAVE_SHIPPING_ADDRESS';