
export const IMAGE_LIST_REQUEST = 'IMAGE_LIST_REQUEST';
export const IMAGE_LIST_SUCCESS = 'IMAGE_LIST_SUCCESS';
export const IMAGE_LIST_FAIL = 'IMAGE_LIST_FAIL';

export const VENUE_IMAGE_LIST_REQUEST = 'VENUE_IMAGE_LIST_REQUEST';
export const VENUE_IMAGE_LIST_SUCCESS = 'VENUE_IMAGE_LIST_SUCCESS';
export const VENUE_IMAGE_LIST_FAIL = 'VENUE_IMAGE_LIST_FAIL';

export const VENUE_IMAGE_ADD_REQUEST = 'VENUE_IMAGE_ADD_REQUEST';
export const VENUE_IMAGE_ADD_SUCCESS = 'VENUE_IMAGE_ADD_SUCCESS';
export const VENUE_IMAGE_ADD_FAIL = 'VENUE_IMAGE_ADD_FAIL';