



export const PRIVACY_LIST_REQUEST = 'PRIVACY_LIST_REQUEST';
export const PRIVACY_LIST_SUCCESS = 'PRIVACY_LIST_SUCCESS';
export const PRIVACY_LIST_FAIL = 'PRIVACY_LIST_FAIL';

export const TC_LIST_REQUEST = 'TC_LIST_REQUEST';
export const TC_LIST_SUCCESS = 'TC_LIST_SUCCESS';
export const TC_LIST_FAIL = 'TC_LIST_FAIL';

export const FAQ_LIST_REQUEST = 'FAQ_LIST_REQUEST';
export const FAQ_LIST_SUCCESS = 'FAQ_LIST_SUCCESS';
export const FAQ_LIST_FAIL = 'FAQ_LIST_FAIL';