


export const CREATE_ORDER_REQUEST ="CREATE_ORDER_REQUEST";
export const CREATE_ORDER_SUCCESS ="CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_FAIL ="CREATE_ORDER_FAIL";
export const CREATE_ORDER_RESET = "CREATE_ORDER_RESET"


export const USER_ORDER_REQUEST = "USER_ORDER_REQUEST";
export const USER_ORDER_SUCCESS = "USER_ORDER_SUCCESS";
export const USER_ORDER_FAIL = "USER_ORDER_FAIL";


export const CHECK_AVAILABLE_REQUEST = 'CHECK_AVAILABLE_REQUEST'
export const CHECK_AVAILABLE_SUCCESS = 'CHECK_AVAILABLE_SUCCESS'
export const CHECK_AVAILABLE_FAIL = "CHECK_AVAILABLE_FAIL"
export const CHECK_AVAILABLE_RESET = 'CHECK_AVAILABLE_RESET'