



export const USER_OTP_SEND_REQUEST = 'USER_OTP_SEND_REQUEST'
export const USER_OTP_SEND_SUCCESS = 'USER_OTP_SEND_SUCCESS'
export const USER_OTP_SEND_FAIL = 'USER_OTP_SEND_FAIL'

export const USER_OTP_VERIFY_REQUEST = 'USER_OTP_VERIFY_REQUEST'
export const USER_OTP_VERIFY_SUCCESS = 'USER_OTP_VERIFY_SUCCESS'
export const USER_OTP_VERIFY_FAIL = 'USER_OTP_VERIFY_FAIL'


export const USER_PASSWORD_FORGET_OTP_SEND_REQUEST = 'USER_PASSWORD_FORGET_OTP_SEND_REQUEST'
export const USER_PASSWORD_FORGET_OTP_SEND_SUCCESS = 'USER_PASSWORD_FORGET_OTP_SEND_SUCCESS'
export const USER_PASSWORD_FORGET_OTP_SEND_FAIL = 'USER_PASSWORD_FORGET_OTP_SEND_FAIL'

export const USER_PASSWORD_FORGET_OTP_VERIFY_REQUEST = 'USER_PASSWORD_FORGET_OTP_VERIFY_REQUEST'
export const USER_PASSWORD_FORGET_OTP_VERIFY_SUCCESS = 'USER_PASSWORD_FORGET_OTP_VERIFY_SUCCESS'
export const USER_PASSWORD_FORGET_OTP_VERIFY_FAIL = 'USER_PASSWORD_FORGET_OTP_VERIFY_FAIL'