export const PAY_ORDER_REQUEST = "PAY_ORDER_REQUEST";
export const PAY_ORDER_SUCCESS = "PAY_ORDER_SUCCESS";
export const PAY_ORDER_FAIL = "PAY_ORDER_FAIL";



export const PAY_REQUEST = "PAY_REQUEST"
export const PAY_SUCCESS = "PAY_SUCCESS"
export const PAY_FAIL = "PAY_FAIL"