export const VENUE_SERVICE_LIST_REQUEST ='VENUE_SERVICE_LIST_REQUEST'
export const VENUE_SERVICE_LIST_SUCCESS ='VENUE_SERVICE_LIST_SUCCESS'
export const VENUE_SERVICE_LIST_FAIL ='VENUE_SERVICE_LIST_FAIL'



export const SERVICE_TYPE_LIST_REQUEST = 'SERVICE_TYPE_LIST_REQUEST'
export const SERVICE_TYPE_LIST_SUCCESS = 'SERVICE_TYPE_LIST_SUCCESS';
export const SERVICE_TYPE_LIST_FAIL = 'SERVICE_TYPE_LIST_FAIL';

export const SERVICE_TYPE_DETAILS_REQUEST = 'SERVICE_TYPE_DETAILS_REQUEST';
export const SERVICE_TYPE_DETAILS_SUCCESS = 'SERVICE_TYPE_DETAILS_SUCCESS';
export const SERVICE_TYPE_DETAILS_FAIL = 'SERVICE_TYPE_DETAILS_FAIL';

export const SERVICE_LIST_REQUEST ='SERVICE_LIST_REQUEST'
export const SERVICE_LIST_SUCCESS ='SERVICE_LIST_SUCCESS'
export const SERVICE_LIST_FAIL ='SERVICE_LIST_FAIL'

export const SERVICE_ADD_REQUEST = 'SERVICE_ADD_REQUEST'
export const SERVICE_ADD_SUCCESS = 'SERVICE_ADD_SUCCESS'
export const SERVICE_ADD_FAIL = 'SERVICE_ADD_FAIL'



export const SERVICE_UPDATE_REQUEST = 'SERVICE_UPDATE_REQUEST'
export const SERVICE_UPDATE_SUCCESS = 'SERVICE_UPDATE_SUCCESS'
export const SERVICE_UPDATE_FAIL = 'SERVICE_UPDATE_FAIL'
export const SERVICE_UPDATE_RESET = 'SERVICE_UPDATE_RESET'


export const SERVICE_DETAILS_REQUEST = 'SERVICE_DETAILS_REQUEST';
export const SERVICE_DETAILS_SUCCESS = 'SERVICE_DETAILS_SUCCESS';
export const SERVICE_DETAILS_FAIL = 'SERVICE_DETAILS_FAIL';

export const VENDOR_SERVICE_DETAILS_REQUEST = 'VENDOR_SERVICE_DETAILS_REQUEST';
export const VENDOR_SERVICE_DETAILS_SUCCESS = 'VENDOR_SERVICE_DETAILS_SUCCESS';
export const VENDOR_SERVICE_DETAILS_FAIL = 'VENDOR_SERVICE_DETAILS_FAIL';