
export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';

export const USER_SIGNIN_REQUEST = 'USER_SIGNIN_REQUEST';
export const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS';
export const USER_SIGNIN_FAIL = 'USER_SIGNIN_FAIL';
export const USER_SIGNOUT  = 'USER_SIGNOUT'



export const USER_PROFILE_REQUEST = 'USER_PROFILE_REQUEST';
export const USER_PROFILE_SUCCESS = 'USER_PROFILE_SUCCESS';
export const USER_PROFILE_FAIL = 'USER_PROFILE_FAIL';


export const USER_TYPE_DETAILS_LIST_REQUEST = 'USER_TYPE_DETAILS_LIST_REQUEST'
export const USER_TYPE_DETAILS_LIST_SUCCESS = 'USER_TYPE_DETAILS_LIST_SUCCESS'
export const USER_TYPE_DETAILS_LIST_FAIL = 'USER_TYPE_DETAILS_LIST_FAIL'




export const USER_ADDRESS_MAP_CONFIRM = 'USER_ADDRESS_MAP_CONFIRM';