export const VENDOR_CITY_REQUEST = 'VENDOR_CITY_REQUEST'
export const VENDOR_CITY_SUCCESS = 'VENDOR_CITY_SUCCESS'
export const VENDOR_CITY_FAIL = 'VENDOR_CITY_FAIL'



export const VENDOR_TYPE_REQUEST = 'VENDOR_TYPE_REQUEST'
export const VENDOR_TYPE_SUCCESS = 'VENDOR_TYPE_SUCCESS'
export const VENDOR_TYPE_FAIL = 'VENDOR_TYPE_FAIL'
