export const VENDOR_CITY_REQUEST = 'VENDOR_CITY_REQUEST'
export const VENDOR_CITY_SUCCESS = 'VENDOR_CITY_SUCCESS'
export const VENDOR_CITY_FAIL = 'VENDOR_CITY_FAIL'



export const VENDOR_TYPE_REQUEST = 'VENDOR_TYPE_REQUEST'
export const VENDOR_TYPE_SUCCESS = 'VENDOR_TYPE_SUCCESS'
export const VENDOR_TYPE_FAIL = 'VENDOR_TYPE_FAIL'



export const VENDOR_REGISTER_REQUEST = 'VENDOR_REGISTER_REQUEST';
export const VENDOR_REGISTER_SUCCESS = 'VENDOR_REGISTER_SUCCESS';
export const VENDOR_REGISTER_FAIL = 'VENDOR_REGISTER_FAIL';

export const VENDOR_SIGNIN_REQUEST = 'VENDOR_SIGNIN_REQUEST';
export const VENDOR_SIGNIN_SUCCESS = 'VENDOR_SIGNIN_SUCCESS';
export const VENDOR_SIGNIN_FAIL = 'VENDOR_SIGNIN_FAIL';
export const VENDOR_SIGNOUT  = 'VENDOR_SIGNOUT'



export const VENDOR_GST_PAN_ADD_REQUEST = 'VENDOR_GST_PAN_ADD_REQUEST';
export const VENDOR_GST_PAN_ADD_SUCCESS = 'VENDOR_GST_PAN_ADD_SUCCESS';
export const VENDOR_GST_PAN_ADD_FAIL = 'VENDOR_GST_PAN_ADD_FAIL';


export const VENDOR_VENUE_LIST_REQUEST = 'VENDOR_VENUE_LIST_REQUEST';
export const VENDOR_VENUE_LIST_SUCCESS = 'VENDOR_VENUE_LIST_SUCCESS';
export const VENDOR_VENUE_LIST_FAIL = 'VENDOR_VENUE_LIST_FAIL';

