export const VENUE_LIST_REQUEST ='VENUE_LIST_REQUEST'
export const VENUE_LIST_SUCCESS ='VENUE_LIST_SUCCESS'
export const VENUE_LIST_FAIL ='VENUE_LIST_FAIL'


export const VENUE_SERVICE_LIST_REQUEST ='VENUE_SERVICE_LIST_REQUEST'
export const VENUE_SERVICE_LIST_SUCCESS ='VENUE_SERVICE_LIST_SUCCESS'
export const VENUE_SERVICE_LIST_FAIL ='VENUE_SERVICE_LIST_FAIL'


export const VENUE_DETAILS_REQUEST = 'VENUE_DETAILS_REQUEST'
export const VENUE_DETAILS_SUCCESS = 'VENUE_DETAILS_SUCCESS'
export const VENUE_DETAILS_FAIL = 'VENUE_DETAILS_FAIL'



export const VENUE_GALLERY_REQUEST = 'VENUE_GALLERY_REQUEST';
export const VENUE_GALLERY_SUCCESS = 'VENUE_GALLERY_SUCCESS';
export const VENUE_GALLERY_FAIL = 'VENUE_GALLERY_FAIL';


export const VENUE_TYPE_LIST_REQUEST = 'VENUE_TYPE_LIST_REQUEST';
export const VENUE_TYPE_LIST_SUCCESS = 'VENUE_TYPE_LIST_SUCCESS';
export const VENUE_TYPE_LIST_Fail = 'VENUE_TYPE_LIST_Fail';

export const VENUE_ADD_REQUEST = 'VENUE_ADD_REQUEST';
export const VENUE_ADD_SUCCESS = 'VENUE_ADD_SUCCESS';
export const VENUE_ADD_Fail = 'VENUE_ADD_Fail';


export const VENUE_UPDATE_REQUEST = 'VENUE_UPDATE_REQUEST';
export const VENUE_UPDATE_SUCCESS = 'VENUE_UPDATE_SUCCESS';
export const VENUE_UPDATE_FAIL = 'VENUE_UPDATE_FAIL';