export const VENUE_LIST_REQUEST ='VENUE_LIST_REQUEST'
export const VENUE_LIST_SUCCESS ='VENUE_LIST_SUCCESS'
export const VENUE_LIST_FAIL ='VENUE_LIST_FAIL'





export const VENUE_DETAILS_REQUEST = 'VENUE_DETAILS_REQUEST'
export const VENUE_DETAILS_SUCCESS = 'VENUE_DETAILS_SUCCESS'
export const VENUE_DETAILS_FAIL = 'VENUE_DETAILS_FAIL'



export const VENUE_GALLERY_REQUEST = 'VENUE_GALLERY_REQUEST';
export const VENUE_GALLERY_SUCCESS = 'VENUE_GALLERY_SUCCESS';
export const VENUE_GALLERY_FAIL = 'VENUE_GALLERY_FAIL';


export const VENUE_TYPE_LIST_REQUEST = 'VENUE_TYPE_LIST_REQUEST';
export const VENUE_TYPE_LIST_SUCCESS = 'VENUE_TYPE_LIST_SUCCESS';
export const VENUE_TYPE_LIST_Fail = 'VENUE_TYPE_LIST_Fail';

export const VENUE_ADD_REQUEST = 'VENUE_ADD_REQUEST';
export const VENUE_ADD_SUCCESS = 'VENUE_ADD_SUCCESS';
export const VENUE_ADD_Fail = 'VENUE_ADD_Fail';

export const VENDOR_VENUE_DETAILS_REQUEST= 'VENDOR_VENUE_DETAILS_REQUEST'
export const VENDOR_VENUE_DETAILS_SUCCESS= 'VENDOR_VENUE_DETAILS_SUCCESS'
export const VENDOR_VENUE_DETAILS_FAIL= 'VENDOR_VENUE_DETAILS_FAIL'
export const VENUE_ADD_RESET = 'VENUE_ADD_RESET'


export const VENUE_UPDATE_REQUEST = 'VENUE_UPDATE_REQUEST';
export const VENUE_UPDATE_SUCCESS = 'VENUE_UPDATE_SUCCESS';
export const VENUE_UPDATE_FAIL = 'VENUE_UPDATE_FAIL';
export const VENUE_UPDATE_RESET ='VENUE_UPDATE_RESET';




export const VENUE_DELETE_REQUEST = 'VENUE_DELETE_REQUEST'
export const VENUE_DELETE_SUCCESS = 'VENUE_DELETE_SUCCESS'
export const VENUE_DELETE_FAIL = 'VENUE_DELETE_FAIL'
export const VENUE_DELETE_RESET = 'VENUE_DELETE_RESET'


export const CITY_VENUE_LIST_REQUEST = 'CITY_VENUE_LIST_REQUEST';
export const CITY_VENUE_LIST_SUCCESS = 'CITY_VENUE_LIST_SUCCESS'
export const CITY_VENUE_LIST_FAIL = 'CITY_VENUE_LIST_FAIL'